runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app

libraries:
- name: flask
  version: "0.12"
- name: numpy
  version: "1.6.1"
- name: PIL
  version: "1.1.7"
- name: pytz
  version: "2017.3"
- name: ssl
  version: "2.7.11"
