runtime: python37

instance_class: F4

handlers:
- url: /robots\.txt
  mime_type: text/plain
  static_files: robots.txt
  upload: robots\.txt
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
